namespace WinPilot.Models;

/// <summary>
/// 검진 종류/검사 항목별 SamFile 엔티티 구조 정의.
/// 키 = "검진종류/검사항목" (예: "암검진/간암1차"). 필드는 나열 순서대로 누적 배치된다.
/// </summary>
public static class SamSchemas
{
    private static readonly Dictionary<string, List<SamContext>> Map = new()
    {
        ["암검진/위암"]              = StomachCancer(),
        ["암검진/대장암1차"]        = ColonCancer(),
        ["암검진/대장암2차"]        = ColonCancer(),
        ["암검진/간암1차"]          = LiverCancer(),
        ["암검진/간암2차"]          = LiverCancer(),
        ["암검진/유방암"]           = BreastCancer(),
        ["암검진/자궁경부암"]       = UterineCancer(),
    };

    /// <summary>정의된 스키마 반환. 없으면 null.</summary>
    public static List<SamContext>? Get(string category, string subType)
        => Map.TryGetValue($"{category}/{subType}", out var s) ? s : null;

    // ─── 암검진 · 위암 ───────────────────────────────────────
    // CancerStomachResult2026.Get위내시경Body() + Get위암BodyLower()
    private static List<SamContext> StomachCancer() => new()
    {
        new PropertySamContext(2, "내시경_관찰소견1"),
        new BooleanStringSamContext("내시경_소견1_위저부"),
        new BooleanStringSamContext("내시경_소견1_위체부"),
        new BooleanStringSamContext("내시경_소견1_위전정"),
        new BooleanStringSamContext("내시경_소견1_위분문"),
        new BooleanStringSamContext("내시경_소견1_소만"),
        new BooleanStringSamContext("내시경_소견1_대만"),
        new BooleanStringSamContext("내시경_소견1_전벽"),
        new BooleanStringSamContext("내시경_소견1_후벽"),

        new PropertySamContext(2, "내시경_관찰소견2"),
        new BooleanStringSamContext("내시경_소견2_위저부"),
        new BooleanStringSamContext("내시경_소견2_위체부"),
        new BooleanStringSamContext("내시경_소견2_위전정"),
        new BooleanStringSamContext("내시경_소견2_위분문"),
        new BooleanStringSamContext("내시경_소견2_소만"),
        new BooleanStringSamContext("내시경_소견2_대만"),
        new BooleanStringSamContext("내시경_소견2_전벽"),
        new BooleanStringSamContext("내시경_소견2_후벽"),

        new PropertySamContext(2, "내시경_관찰소견3"),
        new BooleanStringSamContext("내시경_소견3_위저부"),
        new BooleanStringSamContext("내시경_소견3_위체부"),
        new BooleanStringSamContext("내시경_소견3_위전정"),
        new BooleanStringSamContext("내시경_소견3_위분문"),
        new BooleanStringSamContext("내시경_소견3_소만"),
        new BooleanStringSamContext("내시경_소견3_대만"),
        new BooleanStringSamContext("내시경_소견3_전벽"),
        new BooleanStringSamContext("내시경_소견3_후벽"),

        new BooleanStringSamContext("내시경_기타_식도위정맥류"),
        new BooleanStringSamContext("내시경_기타_식도염"),
        new BooleanStringSamContext("내시경_기타_식도점막하종양"),
        new BooleanStringSamContext("내시경_기타_식도암"),
        new BooleanStringSamContext("내시경_기타_십이지장궤양"),
        new BooleanStringSamContext("내시경_기타_십이지장악성종양"),
        new BooleanStringSamContext("내시경_기타_십이지장점막하종양"),
        new BooleanStringSamContext("내시경_기타_직접기입"),
        new PropertySamContext(40, "내시경_기타_직접기입_텍스트"),

        new PropertySamContext(1, "조직검사"),
        new PropertySamContext(1, "포셉"),
        new PropertySamContext(2, "위조직진단"),
        new BooleanStringSamContext("조직진단암종_관상샘암종_고분화"),
        new BooleanStringSamContext("조직진단암종_관상샘암종_중분화"),
        new BooleanStringSamContext("조직진단암종_관상샘암종_저분화"),
        new BooleanStringSamContext("조직진단암종_유두상샘암종"),
        new BooleanStringSamContext("조직진단암종_반지세포암종"),
        new BooleanStringSamContext("조직진단암종_위림프종_저도"),
        new BooleanStringSamContext("조직진단암종_위림프종_고도"),
        new BooleanStringSamContext("조직진단암종_점액샘암종"),
        new BooleanStringSamContext("조직진단암종_샘편평상피암종"),
        new BooleanStringSamContext("조직진단암종_편평상피암종"),
        new BooleanStringSamContext("조직진단암종_소세포암종"),
        new BooleanStringSamContext("조직진단암종_미분화암종"),
        new BooleanStringSamContext("조직진단암종_신경내분비종양"),
        new BooleanStringSamContext("조직진단암종_직접기입"),
        new PropertySamContext(40, "조직진단암종_직접기입_텍스트"),

        new BooleanStringSamContext("조직진단기타_위비상피성종양"),
        new BooleanStringSamContext("조직진단기타_식도염"),
        new BooleanStringSamContext("조직진단기타_식도암종"),
        new BooleanStringSamContext("조직진단기타_식도점막하종양"),
        new BooleanStringSamContext("조직진단기타_십이지장궤양"),
        new BooleanStringSamContext("조직진단기타_십이지장암종"),
        new BooleanStringSamContext("조직진단기타_십이지장점막하종양"),
        new BooleanStringSamContext("조직진단기타_직접기입"),
        new PropertySamContext(40, "조직진단기타_직접기입_텍스트"),

        new PropertySamContext(1, "검진장소"),
        new DateTimeSamContext("yyyyMMdd", "검진일자"),
        new BooleanStringSamContext("기존위암환자"),
        new PropertySamContext(1, "판정구분"),
        new PropertySamContext(40, "판정구분_기타"),
        new PropertySamContext(600, "권고사항"),

        new DateTimeSamContext("yyyyMMdd", "판정일자"),
        new PropertySamContext(10, "판정의사.doctLicense"),
        new PropertySamContext(12, "판정의사.emplNm"),
        new PropertySamContext(13, "판정의사.peopid"),
        new PropertySamContext(1, "상담료"),
        new PropertySamContext(10, "검사의사_면허번호"),
        new PropertySamContext(12, "검사의사_이름"),
        new PropertySamContext(10, "병리진단의사_면허번호"),
        new PropertySamContext(12, "병리진단의사_이름"),
        new PropertySamContext(1, "장애인_안전편의관리"),
        new BooleanStringSamContext("조직검사_별도청구", "ITEM636"),
        new BooleanStringSamContext("주사약제_아트로핀", "ITEM637"),
        new SpaceConstSamContext(1, "주사약제_부스코판"),
        new BooleanStringSamContext("주사약제_부틸스코폴라민브롬화물", "ITEM639"),
        new BooleanStringSamContext("주사약제_시메트로퓸브롬화물", "ITEM640"),
    };

    // ─── 암검진 · 대장암 ─────────────────────────────────────
    // CancerColonoscopyResult2026.Get대장내시경조직분변Contexts()
    private static List<SamContext> ColonCancer() => new()
    {
        new SpaceConstSamContext(1),
        new PropertySamContext(1, "내시경_맹장삽입여부"),
        new PropertySamContext(1, "내시경_장정결도"),

        new PropertySamContext(1, "내시경_관찰소견1"),
        new BooleanStringSamContext("내시경_위치1_회장말단부"),
        new BooleanStringSamContext("내시경_위치1_맹장"),
        new BooleanStringSamContext("내시경_위치1_상행결장"),
        new BooleanStringSamContext("내시경_위치1_간만곡"),
        new BooleanStringSamContext("내시경_위치1_횡행결장"),
        new BooleanStringSamContext("내시경_위치1_비만곡"),
        new BooleanStringSamContext("내시경_위치1_하행결장"),
        new BooleanStringSamContext("내시경_위치1_에스결장"),
        new BooleanStringSamContext("내시경_위치1_직장"),
        new BooleanStringSamContext("내시경_위치1_항문"),

        new PropertySamContext(1, "내시경_관찰소견2"),
        new BooleanStringSamContext("내시경_위치2_회장말단부"),
        new BooleanStringSamContext("내시경_위치2_맹장"),
        new BooleanStringSamContext("내시경_위치2_상행결장"),
        new BooleanStringSamContext("내시경_위치2_간만곡"),
        new BooleanStringSamContext("내시경_위치2_횡행결장"),
        new BooleanStringSamContext("내시경_위치2_비만곡"),
        new BooleanStringSamContext("내시경_위치2_하행결장"),
        new BooleanStringSamContext("내시경_위치2_에스결장"),
        new BooleanStringSamContext("내시경_위치2_직장"),
        new BooleanStringSamContext("내시경_위치2_항문"),

        new PropertySamContext(1, "내시경_관찰소견3"),
        new BooleanStringSamContext("내시경_위치3_회장말단부"),
        new BooleanStringSamContext("내시경_위치3_맹장"),
        new BooleanStringSamContext("내시경_위치3_상행결장"),
        new BooleanStringSamContext("내시경_위치3_간만곡"),
        new BooleanStringSamContext("내시경_위치3_횡행결장"),
        new BooleanStringSamContext("내시경_위치3_비만곡"),
        new BooleanStringSamContext("내시경_위치3_하행결장"),
        new BooleanStringSamContext("내시경_위치3_에스결장"),
        new BooleanStringSamContext("내시경_위치3_직장"),
        new BooleanStringSamContext("내시경_위치3_항문"),

        new PropertySamContext(3, "내시경_대장폴립"),
        new PropertySamContext(1, "내시경_절제처치"),
        new PropertySamContext(1, "내시경_전처치재료"),
        new BooleanStringSamContext("내시경_기타_치핵"),
        new BooleanStringSamContext("내시경_기타_비특이성장염"),
        new BooleanStringSamContext("내시경_기타_허혈성장염"),
        new BooleanStringSamContext("내시경_기타_궤양성대장"),
        new BooleanStringSamContext("내시경_기타_크론병"),
        new BooleanStringSamContext("내시경_기타_장결핵"),
        new BooleanStringSamContext("내시경_기타_대장게실증"),
        new BooleanStringSamContext("내시경_기타_대장점막하종양"),
        new BooleanStringSamContext("내시경_기타_림프구증식"),
        new BooleanStringSamContext("내시경_기타_직접기입"),
        new PropertySamContext(40, "내시경_기타_직접기입_텍스트"),

        new PropertySamContext(1, "조직검사"),
        new BooleanStringSamContext("조직검사_별도청구", "ITEM609"),
        new PropertySamContext(1, "포셉"),
        new PropertySamContext(1, "대장조직진단"),
        new BooleanStringSamContext("암_샘암종_고분화"),
        new BooleanStringSamContext("암_샘암종_중분화"),
        new BooleanStringSamContext("암_샘암종_저분화"),
        new BooleanStringSamContext("암_점액샘암종"),
        new BooleanStringSamContext("암_반지세포"),
        new BooleanStringSamContext("암_샘편평상피암종"),
        new BooleanStringSamContext("암_편평상피암종"),
        new BooleanStringSamContext("암_소세포암종"),
        new BooleanStringSamContext("암_수질암종"),
        new BooleanStringSamContext("암_미분화암종"),
        new BooleanStringSamContext("암_악성림프종"),
        new BooleanStringSamContext("암_신경내분비종양"),
        new BooleanStringSamContext("암_직접기입"),
        new PropertySamContext(40, "암_직접기입_텍스트"),
        new BooleanStringSamContext("기타7_신경내분비종양"),
        new BooleanStringSamContext("기타7_비상피성종양"),
        new BooleanStringSamContext("기타7_항문암"),
        new BooleanStringSamContext("기타7_말단회장부위암"),
        new BooleanStringSamContext("기타7_직접기입"),
        new PropertySamContext(40, "기타7_직접기입_텍스트"),
        new PropertySamContext(1, "내시경_검진장소"),
        new DateTimeSamContext("yyyyMMdd", "내시경_검진일자"),

        new BooleanStringSamContext("기존대장암환자"),
        new PropertySamContext(1, "분변_판정구분"),
        new SpaceConstSamContext(40),
        new PropertySamContext(600, "분변_권고사항"),

        new PropertySamContext(1, "대장조영_판정구분"),
        new PropertySamContext(20, "대장조영_판정구분_기타"),
        new PropertySamContext(600, "대장조영_권고사항"),

        new PropertySamContext(1, "내시경_판정구분"),
        new PropertySamContext(40, "내시경_판정구분_기타"),
        new PropertySamContext(600, "내시경_권고사항"),

        new DateTimeSamContext("yyyyMMdd", "분변_판정일자"),
        new PropertySamContext(10, "분변_판정의사.doctLicense"),
        new PropertySamContext(12, "분변_판정의사.emplNm"),
        new PropertySamContext(13, "분변_판정의사.peopid"),

        new DateTimeSamContext("yyyyMMdd", "대장조영_판정일자"),
        new PropertySamContext(10, "대장조영_판정의사.doctLicense"),
        new PropertySamContext(12, "대장조영_판정의사.emplNm"),
        new PropertySamContext(13, "대장조영_판정의사.peopid"),

        new DateTimeSamContext("yyyyMMdd", "내시경_판정일자"),
        new PropertySamContext(10, "내시경_판정의사.doctLicense"),
        new PropertySamContext(12, "내시경_판정의사.emplNm"),
        new PropertySamContext(13, "내시경_판정의사.peopid"),

        new PropertySamContext(1, "상담료"),

        new PropertySamContext(10, "대장조영_판독의사_면허번호"),
        new PropertySamContext(12, "대장조영_판독의사_이름"),

        new PropertySamContext(10, "내시경_검사의사_면허번호"),
        new PropertySamContext(12, "내시경_검사의사_이름"),

        new PropertySamContext(10, "내시경_병리진단_면허번호"),
        new PropertySamContext(12, "내시경_병리진단_이름"),

        new PropertySamContext(1, "분변_장애인_안전편의관리"),
        new PropertySamContext(1, "대장조영_장애인_안전편의관리"),
        new PropertySamContext(1, "내시경_장애인_안전편의관리"),
    };

    // ─── 암검진 · 간암 ─────────────────────────────────────────
    // CancerLiverResult2026.Get간암BodyContext()
    private static List<SamContext> LiverCancer() => new()
    {
        new PropertySamContext(1, "검사소견_1"),
        new PropertySamContext(1, "검사소견_2"),
        new PropertySamContext(1, "검사소견_3"),
        new PropertySamContext(1, "검사소견_4"),
        new PropertySamContext(1, "검사소견_5"),
        new PropertySamContext(1, "검사소견_6"),
        new PropertySamContext(1, "검사소견_7"),
        new BooleanStringSamContext("일cm미만_1"),
        new BooleanStringSamContext("일cm미만_2"),
        new BooleanStringSamContext("일cm미만_3"),
        new BooleanStringSamContext("일cm미만_4"),
        new BooleanStringSamContext("일cm미만_5"),
        new BooleanStringSamContext("일cm미만_6"),
        new BooleanStringSamContext("일cm미만_7"),
        new BooleanStringSamContext("일cm미만_8"),
        new BooleanStringSamContext("일cm이상_1"),
        new BooleanStringSamContext("일cm이상_2"),
        new BooleanStringSamContext("일cm이상_3"),
        new BooleanStringSamContext("일cm이상_4"),
        new BooleanStringSamContext("일cm이상_5"),
        new BooleanStringSamContext("일cm이상_6"),
        new BooleanStringSamContext("일cm이상_7"),
        new BooleanStringSamContext("일cm이상_8"),
        new PropertySamContext(3, "병변크기_1"),
        new PropertySamContext(3, "병변크기_2"),
        new PropertySamContext(3, "병변크기_3"),
        new BooleanStringSamContext("기타_담관확장"),
        new BooleanStringSamContext("기타_간내담관결석"),
        new BooleanStringSamContext("기타_복수"),
        new BooleanStringSamContext("기타_비장종대"),
        new BooleanStringSamContext("기타_간문맥_간정맥혈전"),
        new BooleanStringSamContext("기타_담낭이상"),
        new BooleanStringSamContext("기타_기타"),
        new PropertySamContext(40, "기타_담낭이상_텍스트"),
        new PropertySamContext(40, "기타_기타_텍스트"),
        new PropertySamContext(1, "관찰소견_검사방법"),
        new PropertySamContext(1, "관찰소견_일반"),
        new PropertySamContext(6, "관찰소견_정밀_결과"),
        new PropertySamContext(1, "관찰소견_정밀_단위"),
        new PropertySamContext(6, "관찰소견_기준치"),
        new PropertySamContext(1, "검진장소"),
        new DateTimeSamContext("yyyyMMdd", "검진일자"),
        new PropertySamContext(1, "판정구분_판정"),
        new BooleanStringSamContext("기존간암환자"),
        new PropertySamContext(40, "판정구분_기타세부사항"),
        new PropertySamContext(600, "권고사항"),
        new DateTimeSamContext("yyyyMMdd", "판정일자"),
        new PropertySamContext(10, "판정의사.doctLicense"),
        new PropertySamContext(12, "판정의사.emplNm"),
        new PropertySamContext(13, "판정의사.peopid"),
        new PropertySamContext(1, "상담료"),
        new PropertySamContext(10, "검사의사_면허번호"),
        new PropertySamContext(12, "검사의사_이름"),
        new PropertySamContext(1, "장애인_안전편의관리"),
    };

    // ─── 암검진 · 유방암 ─────────────────────────────────────
    // CancerBreastResult2026.Get유방암BodyMiddleContext() + Get유방암BodyLowerContext()
    private static List<SamContext> BreastCancer() => new()
    {
        new PropertySamContext(2, "판독소견1"),
        new BooleanStringSamContext("위치1_R_상외측"),
        new BooleanStringSamContext("위치1_R_상내측"),
        new BooleanStringSamContext("위치1_R_하외측"),
        new BooleanStringSamContext("위치1_R_하내측"),
        new BooleanStringSamContext("위치1_R_유두하부"),
        new BooleanStringSamContext("위치1_R_액와부"),
        new BooleanStringSamContext("위치1_R_직접기입"),
        new PropertySamContext(40, "위치1_R_직접기입_텍스트"),

        new BooleanStringSamContext("위치1_L_상외측"),
        new BooleanStringSamContext("위치1_L_상내측"),
        new BooleanStringSamContext("위치1_L_하외측"),
        new BooleanStringSamContext("위치1_L_하내측"),
        new BooleanStringSamContext("위치1_L_유두하부"),
        new BooleanStringSamContext("위치1_L_액와부"),
        new BooleanStringSamContext("위치1_L_직접기입"),
        new PropertySamContext(40, "위치1_L_직접기입_텍스트"),

        new PropertySamContext(2, "판독소견2"),
        new BooleanStringSamContext("위치2_R_상외측"),
        new BooleanStringSamContext("위치2_R_상내측"),
        new BooleanStringSamContext("위치2_R_하외측"),
        new BooleanStringSamContext("위치2_R_하내측"),
        new BooleanStringSamContext("위치2_R_유두하부"),
        new BooleanStringSamContext("위치2_R_액와부"),
        new BooleanStringSamContext("위치2_R_직접기입"),
        new PropertySamContext(40, "위치2_R_직접기입_텍스트"),

        new BooleanStringSamContext("위치2_L_상외측"),
        new BooleanStringSamContext("위치2_L_상내측"),
        new BooleanStringSamContext("위치2_L_하외측"),
        new BooleanStringSamContext("위치2_L_하내측"),
        new BooleanStringSamContext("위치2_L_유두하부"),
        new BooleanStringSamContext("위치2_L_액와부"),
        new BooleanStringSamContext("위치2_L_직접기입"),
        new PropertySamContext(40, "위치2_L_직접기입_텍스트"),

        new PropertySamContext(2, "판독소견3"),
        new BooleanStringSamContext("위치3_R_상외측"),
        new BooleanStringSamContext("위치3_R_상내측"),
        new BooleanStringSamContext("위치3_R_하외측"),
        new BooleanStringSamContext("위치3_R_하내측"),
        new BooleanStringSamContext("위치3_R_유두하부"),
        new BooleanStringSamContext("위치3_R_액와부"),
        new BooleanStringSamContext("위치3_R_직접기입"),
        new PropertySamContext(40, "위치3_R_직접기입_텍스트"),

        new BooleanStringSamContext("위치3_L_상외측"),
        new BooleanStringSamContext("위치3_L_상내측"),
        new BooleanStringSamContext("위치3_L_하외측"),
        new BooleanStringSamContext("위치3_L_하내측"),
        new BooleanStringSamContext("위치3_L_유두하부"),
        new BooleanStringSamContext("위치3_L_액와부"),
        new BooleanStringSamContext("위치3_L_직접기입"),
        new PropertySamContext(40, "위치3_L_직접기입_텍스트"),

        new PropertySamContext(40, "판독소견_직접기입"),

        // Body Lower
        new PropertySamContext(1, "검진장소"),
        new DateTimeSamContext("yyyyMMdd", "검진일자"),
        new PropertySamContext(1, "판정구분"),
        new BooleanStringSamContext("기존유방암환자"),
        new PropertySamContext(600, "권고사항"),
        new DateTimeSamContext("yyyyMMdd", "판정일자"),
        new PropertySamContext(10, "판정의사.doctLicense"),
        new PropertySamContext(12, "판정의사.emplNm"),
        new PropertySamContext(13, "판정의사.peopid"),
        new PropertySamContext(1, "상담료"),
        new PropertySamContext(10, "판독의사_면허번호"),
        new PropertySamContext(12, "판독의사_이름"),
        new PropertySamContext(1, "장애인_안전편의관리"),
    };

    // ─── 암검진 · 자궁경부암 ─────────────────────────────────
    // CancerUterineResult2026.Get자궁경부암BodyContext()
    private static List<SamContext> UterineCancer() => new()
    {
        new PropertySamContext(1, "비중복_검체상태"),
        new PropertySamContext(1, "비중복_자궁경부_선상피세포"),
        new PropertySamContext(1, "비중복_유형별진단_판정"),
        new PropertySamContext(1, "비중복_편평상피_세포이상_판정"),
        new PropertySamContext(1, "비중복_편평상피_세포이상_위험도"),
        new PropertySamContext(1, "비중복_선상피_세포이상_판정"),
        new PropertySamContext(1, "비중복_선상피_세포이상_종양성"),
        new PropertySamContext(40, "비중복_유형별진단_기타"),
        new PropertySamContext(1, "비중복_추가소견_판정"),
        new PropertySamContext(40, "비중복_추가소견_직접기입"),

        new PropertySamContext(1, "중복_검체상태"),
        new PropertySamContext(1, "중복_자궁경부_선상피세포"),
        new PropertySamContext(1, "중복_유형별진단_판정"),
        new PropertySamContext(1, "중복_편평상피_세포이상_판정"),
        new PropertySamContext(1, "중복_편평상피_세포이상_위험도"),
        new PropertySamContext(1, "중복_선상피_세포이상_판정"),
        new PropertySamContext(1, "중복_선상피_세포이상_종양성"),
        new PropertySamContext(40, "중복_유형별진단_기타"),
        new PropertySamContext(1, "중복_추가소견_판정"),
        new PropertySamContext(40, "중복_추가소견_직접기입"),

        new PropertySamContext(1, "검진장소"),
        new DateTimeSamContext("yyyyMMdd", "검진일자"),
        new PropertySamContext(1, "판정구분"),
        new BooleanStringSamContext("기존자궁경부암환자"),
        new PropertySamContext(40, "판정구분_기타"),
        new PropertySamContext(600, "권고사항"),
        new DateTimeSamContext("yyyyMMdd", "판정일자"),
        new PropertySamContext(10, "판정의사.doctLicense"),
        new PropertySamContext(12, "판정의사.emplNm"),
        new PropertySamContext(13, "판정의사.peopid"),
        new PropertySamContext(1, "상담료"),
        new PropertySamContext(10, "검체채취_면허번호"),
        new PropertySamContext(12, "검체채취_이름"),
        new PropertySamContext(10, "병리진단_면허번호"),
        new PropertySamContext(12, "병리진단_이름"),
        new PropertySamContext(1, "장애인_안전편의관리"),
    };
}
